### ISSUE TITLE
python3-smbus Install Error for fpms

### ISSUE THREAD

**Issue by neilmac64** [WLAN-Pi/fpms#32]
Note: this is a build on a Nanopi NEO, not NEO2.

The installation notes state:
_"Before fpms can be installed, some additional python3 modules are required. Complete the following steps:

sudo apt-get update
**sudo apt-get install python3-smbus**
sudo python3 -m pip install pillow"_

root@IG:~# **sudo apt-get install python3-smbus**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-smbus

**Comment by jolla** [comment]
Could you try this WLAN Pi image that is build for the NEO(1)

https://www.icloud.com/iclouddrive/0xYxya3_UCa8eeg3nZfC8SlEQ#wlanpi-neo-v2.0

**Comment by neilmac64** [comment]
Thanks Jerry, that worked a treat.
